trigger:
- Azure-Function-App

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Python Azure Function'
    pool:
      name: 'default'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.12'
    - script: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt
      displayName: 'Install Dependencies'
    - script: |
        zip -r function.zip .
        mkdir -p $(Build.ArtifactStagingDirectory)
        mv function.zip $(Build.ArtifactStagingDirectory)/
      displayName: 'Package Function App'
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: Test
    displayName: 'Run Unit Tests'
    pool:
      name: 'default'
    steps:
    - script: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt
        pytest tests/  # Make sure your test files are in tests/
      displayName: 'Run Python Tests'

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Test
  jobs:
  - job: Deploy
    displayName: 'Deploy Python Function to Azure'
    pool:
      name: 'default'
    steps:
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'AFN-CICD-SVC-CONNECTION'  
        appType: 'functionAppLinux'
        appName: 'collapse-api-func'                 
        package: '$(Pipeline.Workspace)/drop/function.zip'
