name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Setup Node.js
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # Build Phase
    - name: Install dependencies
      run: npm ci
    
    - name: Lint code
      run: npm run lint
    
    - name: Build application
      run: npm run build
    
    # Test Phase
    - name: Run unit tests
      run: npm test -- --coverage --watchAll=false
    
    - name: Upload test coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
    
    # Docker Build and Push Phase
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/snowbored-game:latest
          ${{ secrets.DOCKER_USERNAME }}/snowbored-game:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    # Alternative: Upload Build Artifacts (uncomment if not using Docker)
    # - name: Create build artifacts
    #   run: |
    #     mkdir -p artifacts
    #     cp -r .next artifacts/
    #     cp -r public artifacts/
    #     cp package.json artifacts/
    #     tar -czf snowbored-build-${{ github.sha }}.tar.gz artifacts/
    
    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: snowbored-build-${{ github.sha }}
    #     path: snowbored-build-${{ github.sha }}.tar.gz
    #     retention-days: 30

  # Security scanning
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Run npm audit
      run: npm audit --audit-level moderate
      continue-on-error: true
