name: prog8860-assignment1-premchander

on:
  workflow_dispatch:
  push:
    branches:
      - assignment-1-fe-branch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: Gym
          MYSQL_USER: devdbuser
          MYSQL_PASSWORD: devpwd123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Debug repo structure
      run: |
        echo "Current directory:"
        pwd
        echo "List root:"
        ls -l
        echo "List Assignment-1-PremChander folder:"
        ls -l Assignment-1-PremChander
        echo "List GymManagementSystem folder inside Assignment-1-PremChander:"
        ls -l Assignment-1-PremChander/GymManagementSystem
        echo "List GymManagementSystem-master folder inside GymManagementSystem:"
        ls -l Assignment-1-PremChander/GymManagementSystem/GymManagementSystem-master
        echo "List app folder inside GymManagementSystem-master:"
        ls -l Assignment-1-PremChander/GymManagementSystem/GymManagementSystem-master/app

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python Dependencies
      run: |
        cd Assignment-1-PremChander/GymManagementSystem/GymManagementSystem-master/app
        pip install -r requirements.txt

    - name: Run Tests with Pytest
      run: |
        cd Assignment-1-PremChander/GymManagementSystem/GymManagementSystem-master/app
        pytest

    - name: Stop Running Container if exists
      run: |
        if [ $(docker ps -aq -f name=gym-app) ]; then
          docker rm -f gym-app
        fi

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        IMAGE_NAME=premchanderj/gym-app
        TAG=latest
        GIT_SHA=${{ github.sha }}
        cd Assignment-1-PremChander/GymManagementSystem/GymManagementSystem-master/app
        docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:$GIT_SHA .

    - name: Push Docker Image to Docker Hub
      run: |
        IMAGE_NAME=premchanderj/gym-app
        TAG=latest
        GIT_SHA=${{ github.sha }}
        docker push $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:$GIT_SHA

    - name: Run Docker Container
      run: docker run -d -p 5000:5000 --name gym-app premchanderj/gym-app:latest

    - name: Show Running Containers
      run: docker ps
