name: CI Test Workflow

on:
  push:
    branches:
      - assignment-1-fe-branch

jobs:
  just-print:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "✅ GitHub Actions is working on this branch"
